// biome-ignore-all lint/security/noDangerouslySetInnerHtml: markdown, math, code, and diagram HTML is sanitized or generated by trusted renderers before insertion.
// biome-ignore-all lint/suspicious/noArrayIndexKey: rendered markdown child order is the stable identity for AST child lists.
import yaml from "js-yaml";
import type {
  Blockquote,
  Code,
  FootnoteDefinition,
  FootnoteReference,
  Heading,
  Image,
  List,
  ListItem,
  Paragraph,
  PhrasingContent,
  Root,
  RootContent,
  Table,
  Text,
  Yaml,
} from "mdast";
import type { InlineMath, Math as MathNode } from "mdast-util-math";
import { toString as mdastToString } from "mdast-util-to-string";
import {
  cloneElement,
  createContext,
  Fragment,
  isValidElement,
  type MutableRefObject,
  memo,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { ContextMenu, type ContextMenuItem } from "../components/ContextMenu";
import { Icon } from "../components/icons";
import { TableModal } from "../components/TableModal";
import { changeKindForRange } from "../hooks/useDiff";
import { scrollBehavior } from "../lib/motion";
import { useWorkspaceTrust } from "../security/trust";
import type { ChangeSet, Hunk } from "../tauri/api";
import { hash32 } from "./hash";
import { assignHeadingIds } from "./headingIds";
import { imageSrc as resolveImageSrc } from "./imagePath";
import { renderMermaid } from "./mermaid";
import { safeHref } from "./safeHref";
import { escapeHtml, sanitizeHtml } from "./sanitizeHtml";
import { slugify } from "./slugify";

interface RenderProps {
  root: Root;
  headingRefs: MutableRefObject<Record<string, HTMLElement | null>>;
  toggleTask: (line: number, checked: boolean) => void;
  /** Called when the user finishes a task-row drag. Coordinates are
   *  source line numbers (1-based, inclusive). `newIndent` is the
   *  desired leading-space count for the moved block in source. */
  onMoveTaskBlock?: (
    fromStart: number,
    fromEnd: number,
    anchorLine: number,
    position: "before" | "after",
    newIndent: number,
  ) => void;
  /** Right-click → "Add new task" inserts an empty task as a sibling
   *  immediately after the clicked task's subtree. */
  onInsertTaskAfter?: (startLine: number, endLine: number) => void;
  /** Right-click → "Remove task" deletes the clicked task and its
   *  subtree (start..end source range, 1-based inclusive). */
  onRemoveTaskBlock?: (startLine: number, endLine: number) => void;
  onLinkClick: (href: string) => void;
  diff?: ChangeSet;
  onHunkClick?: (hunk: Hunk) => void;
  collapsed?: Set<string>;
  onToggleSection?: (id: string) => void;
  /** Source-line keyed set of nested-task list folds, owned by App so
   *  the OutlinePane can mirror this state. */
  taskCollapsed?: Set<number>;
  onToggleTaskCollapse?: (line: number) => void;
  /** Active plan path — passed through so per-plan stateful blocks
   *  (e.g. tables that persist column widths) can identify themselves. */
  planPath?: string | null;
  onFrontmatterLinkClick?: (target: FrontmatterLinkTarget) => void;
  /** When `false`, remote (`https://`) image refs are blocked at the
   *  resolver and rendered as the broken-image placeholder. Drives
   *  the workspace-trust gate; defaults to `true` to preserve the
   *  pre-trust-aware behavior for callers that haven't opted in. */
  remoteAllowed?: boolean;
}

export interface FrontmatterLinkTarget {
  repo: string;
  branch: string;
  base: string;
  index: number;
}

const CALLOUT_PREFIX = /^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*(.*)$/;

export const MarkdownRender = memo(function MarkdownRender({
  root,
  headingRefs,
  toggleTask,
  onMoveTaskBlock,
  onInsertTaskAfter,
  onRemoveTaskBlock,
  onLinkClick,
  diff,
  onHunkClick,
  collapsed,
  onToggleSection,
  taskCollapsed,
  onToggleTaskCollapse,
  planPath,
  onFrontmatterLinkClick,
  remoteAllowed = true,
}: RenderProps) {
  // Single shared context-menu slot for task-row right-clicks. Lives
  // here (not per-row) so a click on row B closes the menu opened on
  // row A — same as DocumentBrowser/OutlinePane.
  const [taskMenu, setTaskMenu] = useState<{
    startLine: number;
    endLine: number;
    anchor: { left: number; top: number };
  } | null>(null);
  const headingIds = useMemo(() => assignHeadingIds(root), [root]);
  // Footnote ordinals — assigned in the order references first
  // appear in the document, matching how readers encounter them. The
  // map is keyed by the GFM identifier so refs and definitions agree.
  const { footnoteOrdinals, footnoteDefinitions } = useMemo(
    () => collectFootnotes(root),
    [root],
  );
  const openTaskMenu = useCallback(
    (
      startLine: number,
      endLine: number,
      anchor: { left: number; top: number },
    ) => setTaskMenu({ startLine, endLine, anchor }),
    [],
  );
  const ctx: RenderCtx = useMemo(
    () => ({
      headingRefs,
      toggleTask,
      onMoveTaskBlock,
      onInsertTaskAfter,
      onRemoveTaskBlock,
      openTaskMenu,
      onLinkClick,
      diff,
      onHunkClick,
      headingIds,
      collapsed,
      onToggleSection,
      taskCollapsed,
      onToggleTaskCollapse,
      planPath: planPath ?? null,
      onFrontmatterLinkClick,
      footnoteOrdinals,
      remoteAllowed,
    }),
    [
      headingRefs,
      toggleTask,
      onMoveTaskBlock,
      onInsertTaskAfter,
      onRemoveTaskBlock,
      openTaskMenu,
      onLinkClick,
      diff,
      onHunkClick,
      headingIds,
      collapsed,
      onToggleSection,
      taskCollapsed,
      onToggleTaskCollapse,
      planPath,
      onFrontmatterLinkClick,
      footnoteOrdinals,
      remoteAllowed,
    ],
  );

  // Walk children with a fold stack: when we enter a heading whose id
  // is in `collapsed`, suppress every subsequent block (including
  // deeper headings) until we hit a heading whose depth is
  // equal-or-shallower than the fold's depth.
  const elements: ReactNode[] = [];
  let foldedAtDepth: number | null = null;
  let seenContent = false;
  for (let i = 0; i < root.children.length; i++) {
    const node = root.children[i];
    if (node.type === "heading") {
      // Exiting an active fold once we hit an equal-or-shallower heading.
      if (foldedAtDepth !== null && node.depth <= foldedAtDepth) {
        foldedAtDepth = null;
      }
      if (foldedAtDepth !== null) continue; // hidden inside parent fold
      elements.push(renderBlock(node, i, ctx, !seenContent));
      seenContent = true;
      const startLine = node.position?.start.line ?? 0;
      const id = headingIds.get(startLine);
      if (id && collapsed?.has(id)) {
        foldedAtDepth = node.depth;
      }
      continue;
    }
    if (foldedAtDepth !== null) continue;
    const isFirstContent = !seenContent && node.type !== "yaml";
    elements.push(renderBlock(node, i, ctx, isFirstContent));
    if (node.type !== "yaml") seenContent = true;
  }

  const taskMenuItems: ContextMenuItem[] = taskMenu
    ? [
        {
          label: "Add new task",
          disabled: !onInsertTaskAfter,
          onSelect: () =>
            onInsertTaskAfter?.(taskMenu.startLine, taskMenu.endLine),
        },
        {
          label: "Remove task",
          danger: true,
          disabled: !onRemoveTaskBlock,
          onSelect: () =>
            onRemoveTaskBlock?.(taskMenu.startLine, taskMenu.endLine),
        },
      ]
    : [];

  return (
    <InlineCtx.Provider value={ctx}>
      {elements}
      {footnoteDefinitions.length > 0 && (
        <FootnotesAside
          definitions={footnoteDefinitions}
          ordinals={footnoteOrdinals}
        />
      )}
      {taskMenu && (
        <ContextMenu
          anchor={taskMenu.anchor}
          items={taskMenuItems}
          onClose={() => setTaskMenu(null)}
        />
      )}
    </InlineCtx.Provider>
  );
}, areRenderPropsEqual);

function areRenderPropsEqual(prev: RenderProps, next: RenderProps): boolean {
  return (
    prev.root === next.root &&
    prev.headingRefs === next.headingRefs &&
    prev.toggleTask === next.toggleTask &&
    prev.onMoveTaskBlock === next.onMoveTaskBlock &&
    prev.onInsertTaskAfter === next.onInsertTaskAfter &&
    prev.onRemoveTaskBlock === next.onRemoveTaskBlock &&
    prev.onLinkClick === next.onLinkClick &&
    prev.diff === next.diff &&
    prev.onHunkClick === next.onHunkClick &&
    prev.collapsed === next.collapsed &&
    prev.onToggleSection === next.onToggleSection &&
    prev.taskCollapsed === next.taskCollapsed &&
    prev.onToggleTaskCollapse === next.onToggleTaskCollapse &&
    prev.planPath === next.planPath &&
    prev.onFrontmatterLinkClick === next.onFrontmatterLinkClick &&
    prev.remoteAllowed === next.remoteAllowed
  );
}

interface RenderCtx {
  headingRefs: MutableRefObject<Record<string, HTMLElement | null>>;
  toggleTask: (line: number, checked: boolean) => void;
  onMoveTaskBlock?: (
    fromStart: number,
    fromEnd: number,
    anchorLine: number,
    position: "before" | "after",
    newIndent: number,
  ) => void;
  onInsertTaskAfter?: (startLine: number, endLine: number) => void;
  onRemoveTaskBlock?: (startLine: number, endLine: number) => void;
  /** Opens the task right-click menu at viewport coordinates. */
  openTaskMenu: (
    startLine: number,
    endLine: number,
    anchor: { left: number; top: number },
  ) => void;
  onLinkClick: (href: string) => void;
  diff?: ChangeSet;
  onHunkClick?: (hunk: Hunk) => void;
  /** Source-line → unique heading id, shared with `extractOutline`. */
  headingIds: Map<number, string>;
  collapsed?: Set<string>;
  onToggleSection?: (id: string) => void;
  taskCollapsed?: Set<number>;
  onToggleTaskCollapse?: (line: number) => void;
  planPath: string | null;
  onFrontmatterLinkClick?: (target: FrontmatterLinkTarget) => void;
  /** Footnote identifier → 1-based ordinal in document order. */
  footnoteOrdinals: Map<string, number>;
  /** Workspace-trust gate — when false, remote image refs are
   *  blocked at the resolver. Local refs unaffected. */
  remoteAllowed: boolean;
}

/** Wraps the rendered block element with `data-source-start-line` /
 *  `data-source-end-line` and a `changed-block changed-<kind>` class
 *  when the block's source range overlaps the diff. The data-attrs go
 *  on every block (changed or not) so onJumpToLine can locate any
 *  block by source line.
 *
 *  Lists are special-cased: data-attrs go on the outer `<ul>` /
 *  `<ol>` (so jump-to-line works), but the changed-block class does
 *  NOT — `ListBlock` decorates each `<li>` individually so each
 *  changed item gets its own margin bar instead of one giant bar
 *  spanning the whole list. */
function decorateBlock(
  node: RootContent,
  inner: ReactNode,
  ctx: RenderCtx,
): ReactNode {
  if (!isValidElement(inner) || !node.position) return inner;
  const startLine = node.position.start.line;
  const endLine = node.position.end.line;
  const props: Record<string, unknown> = {
    "data-source-start-line": startLine,
    "data-source-end-line": endLine,
  };
  const isList = node.type === "list";
  const isHeading = node.type === "heading";
  if (ctx.diff && !isList) {
    const change = changeKindForRange(ctx.diff, startLine, endLine + 1);
    if (change.kind) {
      const existing = (inner.props as { className?: string }).className ?? "";
      props.className =
        `${existing} changed-block changed-${change.kind}`.trim();
      // Headings own their own onClick (collapse toggle); never wire
      // the hunk popover onto a heading or the click would conflict.
      if (!isHeading) {
        props.onClick = (e: React.MouseEvent) => {
          const target = e.target as HTMLElement;
          if (target.closest("a, button, input")) return;
          if (!ctx.onHunkClick || !ctx.diff) return;
          const hunk = firstOverlappingHunk(ctx.diff, startLine, endLine);
          if (hunk) ctx.onHunkClick(hunk);
        };
      }
    }
  }
  return cloneElement(inner, props);
}

function firstOverlappingHunk(
  diff: import("../tauri/api").ChangeSet,
  startLine: number,
  endLine: number,
) {
  return diff.hunks.find((h) => {
    const hStart = h.newStart;
    const hEnd = h.newLines === 0 ? h.newStart : h.newStart + h.newLines - 1;
    return hStart <= endLine && hEnd >= startLine;
  });
}

const InlineCtx = createContext<RenderCtx | null>(null);

function renderBlock(
  node: RootContent,
  key: number,
  ctx: RenderCtx,
  isFirstContent: boolean,
): ReactNode {
  let element: ReactNode;
  switch (node.type) {
    case "yaml":
      element = <FrontmatterStrip key={key} node={node} />;
      break;
    case "heading":
      element = (
        <HeadingBlock
          key={key}
          node={node}
          headingRefs={ctx.headingRefs}
          headingIds={ctx.headingIds}
          collapsed={ctx.collapsed}
          onToggleSection={ctx.onToggleSection}
        />
      );
      break;
    case "paragraph": {
      // Promote image-only paragraphs to a block <figure> so the
      // `<img>` doesn't end up inside a `<p>` (browsers reflow inline
      // images differently from block ones, and we want max-width
      // sizing without a paragraph margin).
      const onlyImage =
        node.children.length === 1 && node.children[0].type === "image";
      if (onlyImage) {
        element = (
          <ImageBlock
            key={key}
            node={node.children[0] as Image}
            planPath={ctx.planPath}
          />
        );
        break;
      }
      element = (
        <p key={key}>
          <RenderInline children_={node.children} />
        </p>
      );
      break;
    }
    case "blockquote":
      element = (
        <BlockquoteBlock
          key={key}
          node={node}
          isFirstContent={isFirstContent}
        />
      );
      break;
    case "list":
      element = <ListBlock key={key} node={node} ctx={ctx} />;
      break;
    case "code":
      if (node.lang === "mermaid") {
        element = <MermaidBlock key={codeBlockKey(node)} source={node.value} />;
      } else {
        element = <CodeBlock key={codeBlockKey(node)} node={node} />;
      }
      break;
    case "math":
      element = <MathBlock key={key} node={node as MathNode} />;
      break;
    case "footnoteDefinition":
      // Definitions are collected at the top of MarkdownRender and
      // emitted once at the bottom inside <aside class="footnotes">.
      // Suppress them in-place so they don't appear twice.
      return null;
    case "table":
      element = <TableBlock key={key} node={node} />;
      break;
    case "thematicBreak":
      element = <hr key={key} />;
      break;
    case "html": {
      const safe = sanitizeHtml((node as { value: string }).value);
      if (!safe) return null;
      element = (
        <div
          key={key}
          className="md-raw-html"
          dangerouslySetInnerHTML={{ __html: safe }}
        />
      );
      break;
    }
    default:
      return null;
  }
  return decorateBlock(node, element, ctx);
}

function HeadingBlock({
  node,
  headingRefs,
  headingIds,
  collapsed,
  onToggleSection,
}: {
  node: Heading;
  headingRefs: MutableRefObject<Record<string, HTMLElement | null>>;
  headingIds: Map<number, string>;
  collapsed?: Set<string>;
  onToggleSection?: (id: string) => void;
}) {
  const line = node.position?.start.line ?? 0;
  // Fall back to a slug if the line isn't in the map (shouldn't happen
  // for parsed headings, but be defensive against AST drift).
  const id = headingIds.get(line) ?? slugify(mdastToString(node));
  const setRef = (el: HTMLElement | null) => {
    headingRefs.current[id] = el;
  };
  const isCollapsed = !!collapsed?.has(id);
  const foldable = !!onToggleSection && node.depth >= 1 && node.depth <= 3;
  const className =
    [foldable ? "heading-foldable" : "", isCollapsed ? "collapsed" : ""]
      .filter(Boolean)
      .join(" ") || undefined;
  const inner = (
    <>
      {foldable && (
        // Hidden from assistive tech so VoiceOver doesn't read
        // "Collapse section button" before every heading. Sighted
        // keyboard users can still Tab to the button (default
        // focusable) and press Enter. This is technically a lint
        // anti-pattern (aria-hidden on focusable element), but the
        // UX call is intentional — VO users almost never fold.
        <button
          type="button"
          className="heading-fold-btn"
          onClick={(e) => {
            e.stopPropagation();
            onToggleSection?.(id);
          }}
        >
          <span className="heading-chevron" aria-hidden="true">
            <Icon.Caret />
          </span>
        </button>
      )}
      <RenderInline children_={node.children} />
    </>
  );
  // Set data-source-* directly here rather than relying on
  // decorateBlock's cloneElement: decorateBlock clones the
  // HeadingBlock *component* element, so any props it adds become
  // ignored component props instead of reaching the rendered <h1>.
  const endLine = node.position?.end.line ?? line;
  switch (node.depth) {
    case 1:
      return (
        <h1
          id={id}
          ref={setRef}
          className={className}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h1>
      );
    case 2:
      return (
        <h2
          id={id}
          ref={setRef}
          className={className}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h2>
      );
    case 3:
      return (
        <h3
          id={id}
          ref={setRef}
          className={className}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h3>
      );
    case 4:
      return (
        <h4
          id={id}
          ref={setRef}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h4>
      );
    case 5:
      return (
        <h5
          id={id}
          ref={setRef}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h5>
      );
    default:
      return (
        <h6
          id={id}
          ref={setRef}
          data-source-start-line={line}
          data-source-end-line={endLine}
        >
          {inner}
        </h6>
      );
  }
}

function FrontmatterStrip({ node }: { node: Yaml }) {
  const ctx = useContext(InlineCtx);
  let data: Record<string, unknown> | null = null;
  try {
    const parsed = yaml.load(node.value);
    if (parsed && typeof parsed === "object") {
      data = parsed as Record<string, unknown>;
    }
  } catch {
    return null;
  }
  if (!data) return null;

  const entries = Object.entries(data);
  return (
    <dl className="doc-frontmatter">
      {entries.map(([key, value]) => (
        <Fragment key={key}>
          <dt>{key}</dt>
          <dd>
            {renderFrontmatterValue(key, value, {
              onLinkClick: ctx?.onFrontmatterLinkClick,
            })}
          </dd>
        </Fragment>
      ))}
    </dl>
  );
}

interface RenderFrontmatterOptions {
  onLinkClick?: (target: FrontmatterLinkTarget) => void;
}

export function renderFrontmatterValue(
  key: string,
  value: unknown,
  options: RenderFrontmatterOptions = {},
): ReactNode {
  if (key === "status" && typeof value === "string") {
    return (
      <span className="fm-status">
        <span className="ds" />
        {value}
      </span>
    );
  }
  if (Array.isArray(value)) {
    if (key === "links") return renderFrontmatterLinks(value, options);
    return renderFrontmatterArray(value);
  }
  if (value instanceof Date) return formatFrontmatterInlineValue(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return value;
  if (typeof value === "boolean") return String(value);
  if (isFrontmatterRecord(value)) return formatFrontmatterRecord(value);
  if (value == null) return "";
  return JSON.stringify(value);
}

function renderFrontmatterArray(value: unknown[]): ReactNode {
  return (
    <span className="fm-chip-list">
      {value.map((v, i) => {
        if (isFrontmatterRecord(v)) {
          return (
            <span className="fm-object-chip" key={i}>
              {formatFrontmatterRecord(v)}
            </span>
          );
        }
        return (
          <span className="tag" key={i}>
            #{formatFrontmatterInlineValue(v)}
          </span>
        );
      })}
    </span>
  );
}

function renderFrontmatterLinks(
  value: unknown[],
  options: RenderFrontmatterOptions,
): ReactNode {
  if (value.length === 0) return "";
  return (
    <span className="fm-links">
      {value.map((link, index) =>
        renderFrontmatterLink(link, index, options.onLinkClick),
      )}
    </span>
  );
}

function renderFrontmatterLink(
  link: unknown,
  index: number,
  onLinkClick?: (target: FrontmatterLinkTarget) => void,
): ReactNode {
  if (!isFrontmatterRecord(link)) {
    return (
      <span className="fm-object-chip" key={index}>
        {formatFrontmatterInlineValue(link)}
      </span>
    );
  }

  const repo = frontmatterString(link.repo);
  const branch = frontmatterString(link.branch);
  const base = frontmatterString(link.base);
  const target =
    repo && branch
      ? {
          repo,
          branch,
          base: base ?? "main",
          index,
        }
      : null;
  const title = [
    repo ? `repo: ${repo}` : null,
    branch ? `branch: ${branch}` : null,
    base ? `base: ${base}` : null,
  ]
    .filter(Boolean)
    .join("\n");
  const body = (
    <>
      <span className="fm-link-repo">{repo ?? "unknown repo"}</span>
      {branch ? (
        <span className="fm-link-branch">
          <Icon.Branch />
          <span className="fm-link-branch-text">{branch}</span>
        </span>
      ) : null}
    </>
  );

  if (target && onLinkClick) {
    return (
      <button
        type="button"
        className="fm-link fm-link-button"
        key={index}
        title={title || undefined}
        onClick={() => onLinkClick(target)}
      >
        {body}
      </button>
    );
  }

  return (
    <span className="fm-link" key={index} title={title || undefined}>
      {body}
    </span>
  );
}

function frontmatterString(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function isFrontmatterRecord(value: unknown): value is Record<string, unknown> {
  return Object.prototype.toString.call(value) === "[object Object]";
}

function formatFrontmatterRecord(value: Record<string, unknown>): string {
  return Object.entries(value)
    .map(([key, item]) => `${key}: ${formatFrontmatterInlineValue(item)}`)
    .join(", ");
}

function formatFrontmatterInlineValue(value: unknown): string {
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value instanceof Date) {
    const time = value.getTime();
    if (Number.isNaN(time)) return String(value);
    const iso = value.toISOString();
    return iso.endsWith("T00:00:00.000Z") ? iso.slice(0, 10) : iso;
  }
  if (Array.isArray(value)) {
    return value.map(formatFrontmatterInlineValue).join(", ");
  }
  if (isFrontmatterRecord(value)) return formatFrontmatterRecord(value);
  if (value == null) return "";
  return JSON.stringify(value);
}

function BlockquoteBlock({
  node,
  isFirstContent,
}: {
  node: Blockquote;
  isFirstContent: boolean;
}) {
  // Detect GitHub-style callouts: first paragraph starts with `[!NOTE]`, etc.
  const firstChild = node.children[0];
  if (firstChild?.type === "paragraph") {
    const firstText = firstChild.children[0];
    if (firstText?.type === "text") {
      const match = firstText.value.match(CALLOUT_PREFIX);
      if (match) {
        const tone =
          match[1] === "IMPORTANT" ||
          match[1] === "WARNING" ||
          match[1] === "CAUTION"
            ? "important"
            : "note";
        const titleText = match[2].trim();
        const title =
          titleText || (tone === "important" ? "Important" : "Note");
        // Body = rest of the first paragraph (after the [!XXX] tag) + subsequent children
        const restOfFirst = firstChild.children.slice(1) as PhrasingContent[];
        const restAsParagraph: Paragraph = {
          type: "paragraph",
          children: restOfFirst,
        };
        const bodyChildren =
          restOfFirst.length > 0
            ? [restAsParagraph, ...node.children.slice(1)]
            : node.children.slice(1);
        return (
          <div className={`callout ${tone}`}>
            <span className="callout-icon">
              {tone === "important" ? <Icon.Bolt /> : <Icon.Note />}
            </span>
            <div>
              <div className="callout-title">{title}</div>
              <div className="callout-text">
                {bodyChildren.map((c, i) =>
                  c.type === "paragraph" ? (
                    <RenderInline key={i} children_={c.children} />
                  ) : null,
                )}
              </div>
            </div>
          </div>
        );
      }
    }
  }
  // Lede: a single-paragraph blockquote at the very top of a doc reads as
  // an italicized intro. Mid-doc single-paragraph blockquotes are asides
  // (e.g. "Deviation: ..."), not ledes — render those as plain blockquotes.
  if (
    isFirstContent &&
    node.children.length === 1 &&
    node.children[0].type === "paragraph"
  ) {
    return (
      <p className="lede">
        <RenderInline children_={(node.children[0] as Paragraph).children} />
      </p>
    );
  }
  // Fallback: standard blockquote
  return (
    <blockquote>
      {node.children.map((c, i) =>
        c.type === "paragraph" ? (
          <p key={i}>
            <RenderInline children_={c.children} />
          </p>
        ) : null,
      )}
    </blockquote>
  );
}

/** Pixel offset between adjacent visual nesting levels in the
 *  rendered task list. Mirrors `.tasks.nested { padding-left }`. */
const VIEWER_INDENT_PX = 24;

/** Default leading-space step we apply when the source contains no
 *  prior nested bullets to learn from. Overwritten on the fly when we
 *  spot an indented bullet during a drag. */
const FALLBACK_SOURCE_INDENT_STEP = 2;

/** Movement threshold (px) before a checkbox/bullet pointerdown is
 *  promoted from a tap-toggle into a drag. Below this, the gesture
 *  resolves into a normal click and the existing onClick handler
 *  toggles the task. */
const TASK_DRAG_THRESHOLD_PX = 4;

/** Pointer-driven drag for task rows. Initiated from the checkbox or
 *  bullet's own pointerdown — we wait for a small movement before
 *  committing to drag mode so a quick click still toggles the task.
 *  All visual state (dim source row, fixed-position ghost, drop
 *  indicator) lives outside React; on release we hand the resolved
 *  destination to App's `onMoveTaskBlock`. */
function startTaskDrag(e: React.PointerEvent, ctx: RenderCtx) {
  if (e.button !== 0) return;
  if (!ctx.onMoveTaskBlock) return;
  const handle = e.currentTarget as HTMLElement;
  const li = handle.closest("li[data-task-line]") as HTMLElement | null;
  if (!li) return;
  const fromStart = parseInt(
    li.getAttribute("data-source-start-line") || "0",
    10,
  );
  const fromEnd = parseInt(li.getAttribute("data-source-end-line") || "0", 10);
  if (!fromStart || !fromEnd) return;

  const startX = e.clientX;
  const startY = e.clientY;
  let dragging = false;
  let indicator: HTMLElement | null = null;
  let ghost: HTMLElement | null = null;
  let ghostOffsetX = 0;
  let ghostOffsetY = 0;
  let indentStep = FALLBACK_SOURCE_INDENT_STEP;
  let drop: {
    anchorLine: number;
    position: "before" | "after";
    newIndent: number;
  } | null = null;

  const beginDrag = (ev: PointerEvent) => {
    dragging = true;
    li.classList.add("dragging");
    document.body.classList.add("task-dragging");

    indicator = document.createElement("div");
    indicator.className = "task-drop-indicator";
    indicator.style.display = "none";
    document.body.appendChild(indicator);

    const sourceHead = li.querySelector(
      ":scope > .task-row-head",
    ) as HTMLElement | null;
    if (sourceHead) {
      const headRect = sourceHead.getBoundingClientRect();
      ghostOffsetX = startX - headRect.left;
      ghostOffsetY = startY - headRect.top;
      ghost = sourceHead.cloneNode(true) as HTMLElement;
      ghost.classList.add("task-drag-ghost");
      ghost.style.width = `${headRect.width}px`;
      ghost.style.left = `${ev.clientX - ghostOffsetX}px`;
      ghost.style.top = `${ev.clientY - ghostOffsetY}px`;
      document.body.appendChild(ghost);
    }

    // Detect the document's indent step from the first nested bullet
    // we can find — comparing all task <li> source columns. Falls back
    // to two spaces if the doc has no nesting yet.
    const allTaskLis = Array.from(
      document.querySelectorAll<HTMLElement>("li[data-task-line]"),
    );
    let detectedStep = 0;
    for (const node of allTaskLis) {
      const col = parseInt(
        node.getAttribute("data-source-start-column") || "1",
        10,
      );
      if (col > 1) {
        const indent = col - 1;
        if (detectedStep === 0 || indent < detectedStep) {
          detectedStep = indent;
        }
      }
    }
    indentStep = detectedStep || FALLBACK_SOURCE_INDENT_STEP;
  };

  const updateDrag = (ev: PointerEvent) => {
    if (!indicator) return;
    const x = ev.clientX;
    const y = ev.clientY;
    if (ghost) {
      ghost.style.left = `${x - ghostOffsetX}px`;
      ghost.style.top = `${y - ghostOffsetY}px`;
    }
    // elementFromPoint returns the topmost element — temporarily hide
    // the ghost and indicator so they don't catch the hit.
    const prevIndicator = indicator.style.display;
    const prevGhost = ghost?.style.display ?? "";
    indicator.style.display = "none";
    if (ghost) ghost.style.display = "none";
    const hit = document.elementFromPoint(x, y) as HTMLElement | null;
    indicator.style.display = prevIndicator;
    if (ghost) ghost.style.display = prevGhost;
    const targetLi = hit?.closest("li[data-task-line]") as HTMLElement | null;
    if (!targetLi || li.contains(targetLi)) {
      indicator.style.display = "none";
      drop = null;
      return;
    }
    const head = targetLi.querySelector(
      ":scope > .task-row-head",
    ) as HTMLElement | null;
    if (!head) {
      indicator.style.display = "none";
      drop = null;
      return;
    }
    const rect = head.getBoundingClientRect();
    const before = y < rect.top + rect.height / 2;
    const targetCol = parseInt(
      targetLi.getAttribute("data-source-start-column") || "1",
      10,
    );
    const targetIndent = Math.max(0, targetCol - 1);
    const targetStart = parseInt(
      targetLi.getAttribute("data-source-start-line") || "0",
      10,
    );
    const targetEnd = parseInt(
      targetLi.getAttribute("data-source-end-line") || "0",
      10,
    );
    if (!targetStart || !targetEnd) {
      indicator.style.display = "none";
      drop = null;
      return;
    }
    // Cursor X relative to target's left edge maps to a level delta:
    // each VIEWER_INDENT_PX past the row's left = +1 deeper (after
    // drops only), each step left = −1 (capped at the doc's
    // outermost level).
    const xRel = x - rect.left;
    let levelDelta = 0;
    if (xRel >= VIEWER_INDENT_PX) {
      levelDelta = before ? 0 : 1;
    } else if (xRel < 0) {
      levelDelta = Math.max(
        -Math.ceil(Math.abs(xRel) / VIEWER_INDENT_PX),
        -Math.floor(targetIndent / indentStep),
      );
    }
    const newIndent = Math.max(0, targetIndent + levelDelta * indentStep);
    const anchorLine = before ? targetStart : targetEnd;
    const position: "before" | "after" = before ? "before" : "after";
    drop = { anchorLine, position, newIndent };

    const indentDeltaPx =
      (newIndent - targetIndent) * (VIEWER_INDENT_PX / indentStep);
    const left = rect.left + indentDeltaPx;
    const top = before ? rect.top - 1 : rect.bottom - 1;
    const width = Math.max(40, rect.right - left);
    indicator.style.cssText = `display:block;position:fixed;left:${left}px;top:${top}px;width:${width}px;`;
  };

  const cleanup = () => {
    document.removeEventListener("pointermove", onMove);
    document.removeEventListener("pointerup", onUp);
    document.removeEventListener("pointercancel", onCancel);
    indicator?.remove();
    ghost?.remove();
    li.classList.remove("dragging");
    document.body.classList.remove("task-dragging");
  };

  const onMove = (ev: PointerEvent) => {
    if (!dragging) {
      const dx = ev.clientX - startX;
      const dy = ev.clientY - startY;
      if (Math.hypot(dx, dy) < TASK_DRAG_THRESHOLD_PX) return;
      beginDrag(ev);
    }
    updateDrag(ev);
  };

  const onUp = () => {
    const wasDragging = dragging;
    const pending = drop;
    cleanup();
    if (!wasDragging) return;
    // The browser will synthesize a click after this pointerup —
    // swallow it once so the checkbox toggle doesn't fire on the
    // mouseup that ended a drag.
    const swallow = (ev: MouseEvent) => {
      ev.preventDefault();
      ev.stopPropagation();
      document.removeEventListener("click", swallow, true);
    };
    document.addEventListener("click", swallow, true);
    if (pending) {
      ctx.onMoveTaskBlock?.(
        fromStart,
        fromEnd,
        pending.anchorLine,
        pending.position,
        pending.newIndent,
      );
    }
  };
  const onCancel = () => cleanup();

  document.addEventListener("pointermove", onMove);
  document.addEventListener("pointerup", onUp);
  document.addEventListener("pointercancel", onCancel);
}

function isTaskListNode(list: List): boolean {
  return list.children.some(
    (c) =>
      c.type === "listItem" && typeof (c as ListItem).checked === "boolean",
  );
}

const EMPTY_TASK_COLLAPSE: Set<number> = new Set();

function ListBlock({ node, ctx }: { node: List; ctx: RenderCtx }) {
  // Task fold state is owned by App so the OutlinePane can mirror it.
  // Falls back to an empty set when the doc is rendered without a host
  // (e.g. tests).
  const collapsed = ctx.taskCollapsed ?? EMPTY_TASK_COLLAPSE;
  const toggleCollapse = ctx.onToggleTaskCollapse ?? (() => {});
  if (isTaskListNode(node)) {
    return (
      <TaskListBranch
        list={node}
        ctx={ctx}
        collapsed={collapsed}
        toggleCollapse={toggleCollapse}
        nested={false}
      />
    );
  }
  return <RegularListBranch list={node} ctx={ctx} />;
}

function TaskListBranch({
  list,
  ctx,
  collapsed,
  toggleCollapse,
  nested,
}: {
  list: List;
  ctx: RenderCtx;
  collapsed: Set<number>;
  toggleCollapse: (line: number) => void;
  nested: boolean;
}) {
  return (
    <ul className={nested ? "tasks nested" : "tasks"}>
      {list.children.map((c, i) => {
        if (c.type !== "listItem") return null;
        const item = c as ListItem;
        const line = item.position?.start.line ?? i;
        const itemEnd = item.position?.end.line ?? line;
        const isTask = typeof item.checked === "boolean";
        const checked = !!item.checked;
        const firstPara = item.children.find((cc) => cc.type === "paragraph") as
          | Paragraph
          | undefined;
        const childLists = item.children.filter(
          (cc) => cc.type === "list",
        ) as List[];
        const hasChildren = childLists.length > 0;
        const isCollapsed = hasChildren && collapsed.has(line);
        const change: { kind: "added" | "modified" | "deleted-near" | null } =
          ctx.diff
            ? changeKindForRange(ctx.diff, line, itemEnd + 1)
            : { kind: null };
        const className = [
          "task-row",
          isTask ? "" : "no-check",
          checked ? "done" : "",
          hasChildren ? "has-children" : "leaf",
          isCollapsed ? "collapsed" : "",
          change.kind ? `changed-block changed-${change.kind}` : "",
        ]
          .filter(Boolean)
          .join(" ");
        const onHeadContextMenu = isTask
          ? (e: React.MouseEvent) => {
              e.preventDefault();
              e.stopPropagation();
              ctx.openTaskMenu(line, itemEnd, {
                left: e.clientX,
                top: e.clientY,
              });
            }
          : undefined;
        // Shift+F10 mirrors the OS keyboard shortcut for "open the
        // context menu for the focused element." Anchored at the row's
        // bottom-left so it hangs below the row instead of off-screen.
        const onHeadKeyDown = isTask
          ? (e: React.KeyboardEvent<HTMLDivElement>) => {
              if (e.key !== "F10" || !e.shiftKey) return;
              e.preventDefault();
              const rect = e.currentTarget.getBoundingClientRect();
              ctx.openTaskMenu(line, itemEnd, {
                left: rect.left,
                top: rect.bottom,
              });
            }
          : undefined;
        const startColumn = item.position?.start.column ?? 1;
        return (
          <li
            key={i}
            className={className}
            data-task-line={line}
            data-source-start-line={line}
            data-source-end-line={itemEnd}
            data-source-start-column={startColumn}
          >
            {/* biome-ignore lint/a11y/noStaticElementInteractions: the row head handles task-list keyboard gestures without taking focus itself. */}
            <div
              className="task-row-head"
              onContextMenu={onHeadContextMenu}
              onKeyDown={onHeadKeyDown}
            >
              {hasChildren && (
                <button
                  type="button"
                  className="task-chevron"
                  onClick={(e) => {
                    e.stopPropagation();
                    toggleCollapse(line);
                  }}
                  aria-label={isCollapsed ? "Expand" : "Collapse"}
                  aria-expanded={!isCollapsed}
                >
                  <Icon.Caret />
                </button>
              )}
              {isTask ? (
                <button
                  type="button"
                  className={`task-check ${checked ? "done" : ""}`}
                  onPointerDown={(e) => {
                    if (e.button !== 0) return;
                    e.stopPropagation();
                    startTaskDrag(e, ctx);
                  }}
                  onClick={(e) => {
                    e.stopPropagation();
                    ctx.toggleTask(line, !checked);
                  }}
                  aria-label={checked ? "Uncheck" : "Check"}
                />
              ) : (
                <span
                  className="task-bullet"
                  aria-hidden="true"
                  onPointerDown={(e) => {
                    if (e.button !== 0) return;
                    e.stopPropagation();
                    startTaskDrag(e, ctx);
                  }}
                />
              )}
              <span className="task-text">
                {firstPara && <RenderInline children_={firstPara.children} />}
              </span>
              <span className="task-line">L{line}</span>
            </div>
            {hasChildren && (
              <div
                className={`task-row-children ${isCollapsed ? "" : "open"}`}
                aria-hidden={isCollapsed}
              >
                <div className="task-row-children-inner">
                  {childLists.map((sub, j) =>
                    isTaskListNode(sub) ? (
                      <TaskListBranch
                        key={j}
                        list={sub}
                        ctx={ctx}
                        collapsed={collapsed}
                        toggleCollapse={toggleCollapse}
                        nested={true}
                      />
                    ) : (
                      <RegularListBranch key={j} list={sub} ctx={ctx} />
                    ),
                  )}
                </div>
              </div>
            )}
          </li>
        );
      })}
    </ul>
  );
}

function RegularListBranch({ list, ctx }: { list: List; ctx: RenderCtx }) {
  const Tag = list.ordered ? "ol" : "ul";
  return (
    <Tag>
      {list.children.map((c, i) => {
        if (c.type !== "listItem") return null;
        const item = c as ListItem;
        const startLine = item.position?.start.line ?? i;
        const endLine = item.position?.end.line ?? startLine;
        const change: { kind: "added" | "modified" | "deleted-near" | null } =
          ctx.diff
            ? changeKindForRange(ctx.diff, startLine, endLine + 1)
            : { kind: null };
        const className = change.kind
          ? `changed-block changed-${change.kind}`
          : undefined;
        const onClick =
          change.kind && ctx.onHunkClick && ctx.diff
            ? (e: React.MouseEvent) => {
                const target = e.target as HTMLElement;
                if (target.closest("a, button, input")) return;
                const diff = ctx.diff;
                if (!diff) return;
                const hunk = firstOverlappingHunk(diff, startLine, endLine);
                if (hunk) ctx.onHunkClick?.(hunk);
              }
            : undefined;
        return (
          // biome-ignore lint/a11y/useKeyWithClickEvents: hunk click is a mouse shortcut; keyboard users use the explicit diff controls.
          <li
            key={i}
            className={className}
            data-source-start-line={startLine}
            data-source-end-line={endLine}
            onClick={onClick}
          >
            {item.children.map((cc, j) => {
              if (cc.type === "paragraph") {
                return <RenderInline key={j} children_={cc.children} />;
              }
              if (cc.type === "list") {
                return <RegularListBranch key={j} list={cc} ctx={ctx} />;
              }
              return null;
            })}
          </li>
        );
      })}
    </Tag>
  );
}

const CodeBlock = memo(function CodeBlock({ node }: { node: Code }) {
  const lang = node.lang ?? "";
  const html = useHighlightedCode(node.value, lang);
  return (
    <pre>
      {lang && <span className="code-lang">{lang}</span>}
      {html != null ? (
        <code
          className="shiki-tokens"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <code>{node.value}</code>
      )}
    </pre>
  );
}, areCodeBlockPropsEqual);

function areCodeBlockPropsEqual(
  prev: { node: Code },
  next: { node: Code },
): boolean {
  return (
    prev.node.value === next.node.value && prev.node.lang === next.node.lang
  );
}

function codeBlockKey(node: Code): string {
  return `code:${node.position?.start.line ?? 0}:${node.value.length}:${hash32(
    node.value,
  )}`;
}

function useHighlightedCode(code: string, lang: string): string | null {
  const [html, setHtml] = useState<string | null>(null);
  useEffect(() => {
    if (!lang) {
      setHtml(null);
      return;
    }
    let cancelled = false;
    void import("./highlight")
      .then(({ highlightCode }) => highlightCode(code, lang))
      .then((out) => {
        if (!cancelled) setHtml(out);
      })
      .catch(() => {
        if (!cancelled) setHtml(null);
      });
    return () => {
      cancelled = true;
    };
  }, [code, lang]);
  return html;
}

type SortDir = "asc" | "desc";

function TableBlock({ node }: { node: Table }) {
  const [head, ...body] = node.children;
  const [modalOpen, setModalOpen] = useState(false);

  return (
    <div className="table-overflow">
      <TableMarkup head={head} body={body} />
      <button
        type="button"
        className="table-expand-btn"
        onClick={() => setModalOpen(true)}
        aria-label="Open table in viewer"
        title="Open in viewer"
      >
        <Icon.Expand />
      </button>
      {modalOpen && (
        <TableViewer
          head={head}
          body={body}
          onClose={() => setModalOpen(false)}
        />
      )}
    </div>
  );
}

/** Modal wrapper that owns view-only controls (wrap toggle) and renders
 *  the same table with sticky header/first-column + resizable columns. */
function TableViewer({
  head,
  body,
  onClose,
}: {
  head: Table["children"][number] | undefined;
  body: Table["children"];
  onClose: () => void;
}) {
  const [wrap, setWrap] = useState(false);
  return (
    <TableModal
      title="Table viewer"
      onClose={onClose}
      headExtras={
        <label className="table-modal-toggle">
          <input
            type="checkbox"
            checked={wrap}
            onChange={(e) => setWrap(e.target.checked)}
          />
          <span>Wrap</span>
        </label>
      }
    >
      <div className={`table-modal-scroll${wrap ? " wrap" : ""}`}>
        <TableMarkup head={head} body={body} sticky resizableColumns />
      </div>
    </TableModal>
  );
}

/** Renders the actual `<table>` markup with sort affordances. Shared
 *  between the in-document table and the modal viewer; each instance
 *  owns its own sort state. `sticky` enables position:sticky on the
 *  header row and first column. `resizableColumns` adds a drag handle
 *  on each th — width state is local to this instance and resets when
 *  the component unmounts (closing the modal returns to natural widths). */
function TableMarkup({
  head,
  body,
  sticky = false,
  resizableColumns = false,
}: {
  head: Table["children"][number] | undefined;
  body: Table["children"];
  sticky?: boolean;
  resizableColumns?: boolean;
}) {
  const [sortKey, setSortKey] = useState<{ col: number; dir: SortDir } | null>(
    null,
  );
  const [colWidths, setColWidths] = useState<Array<number | null>>([]);

  const sortedBody = useMemo(() => {
    if (!sortKey) return body;
    const { col, dir } = sortKey;
    const cellText = (rowIdx: number) => {
      const row = body[rowIdx];
      const cell = row?.children[col];
      return cell ? mdastToString(cell).trim() : "";
    };
    const indices = body.map((_, i) => i);
    const numeric = indices.every((i) => {
      const t = cellText(i);
      return t === "" || /^-?\d+(?:\.\d+)?$/.test(t);
    });
    indices.sort((a, b) => {
      const at = cellText(a);
      const bt = cellText(b);
      let cmp = 0;
      if (numeric) {
        const an = at === "" ? Number.POSITIVE_INFINITY : parseFloat(at);
        const bn = bt === "" ? Number.POSITIVE_INFINITY : parseFloat(bt);
        cmp = an - bn;
      } else {
        cmp = at.localeCompare(bt, undefined, { numeric: true });
      }
      if (cmp === 0) return a - b; // stable
      return dir === "asc" ? cmp : -cmp;
    });
    return indices.map((i) => body[i]);
  }, [body, sortKey]);

  const cycleSort = (col: number) =>
    setSortKey((prev) => {
      if (!prev || prev.col !== col) return { col, dir: "asc" };
      if (prev.dir === "asc") return { col, dir: "desc" };
      return null;
    });

  const startColumnResize =
    (col: number) => (e: React.MouseEvent<HTMLSpanElement>) => {
      e.preventDefault();
      e.stopPropagation();
      const handle = e.currentTarget;
      const th = handle.parentElement as HTMLTableCellElement | null;
      if (!th) return;
      const startWidth = th.getBoundingClientRect().width;
      const startX = e.clientX;
      let raf = 0;
      let latest = startWidth;
      const onMove = (ev: MouseEvent) => {
        if (raf) return;
        raf = requestAnimationFrame(() => {
          raf = 0;
          const next = Math.max(48, startWidth + (ev.clientX - startX));
          latest = next;
          th.style.width = `${next}px`;
        });
      };
      const onUp = () => {
        if (raf) cancelAnimationFrame(raf);
        document.removeEventListener("mousemove", onMove);
        document.removeEventListener("mouseup", onUp);
        document.body.style.cursor = "";
        document.body.style.userSelect = "";
        setColWidths((prev) => {
          const next = [...prev];
          while (next.length <= col) next.push(null);
          next[col] = Math.round(latest);
          return next;
        });
      };
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
      document.body.style.cursor = "col-resize";
      document.body.style.userSelect = "none";
    };

  const classes = [
    sticky ? "table-sticky" : "",
    resizableColumns ? "table-resizable-cols" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <table className={classes || undefined}>
      {head && (
        <thead>
          <tr>
            {head.children.map((cell, j) => {
              const isSorted = sortKey?.col === j;
              const dir = isSorted ? sortKey.dir : null;
              const pinned = colWidths[j];
              return (
                <th
                  key={j}
                  style={pinned != null ? { width: pinned } : undefined}
                  className={isSorted ? `sorted sorted-${dir}` : undefined}
                  aria-sort={
                    isSorted
                      ? dir === "asc"
                        ? "ascending"
                        : "descending"
                      : "none"
                  }
                >
                  <button
                    type="button"
                    className="th-sort-btn"
                    onClick={(e) => {
                      if ((e.target as HTMLElement).closest(".th-resizer"))
                        return;
                      cycleSort(j);
                    }}
                  >
                    <span className="th-text">
                      <RenderInline children_={cell.children} />
                      <span className="th-sort" aria-hidden="true">
                        {dir === "asc" ? "▴" : dir === "desc" ? "▾" : "↕"}
                      </span>
                    </span>
                  </button>
                  {resizableColumns && (
                    <span
                      className="th-resizer"
                      onMouseDown={startColumnResize(j)}
                      title="Drag to resize column"
                      aria-hidden="true"
                    />
                  )}
                </th>
              );
            })}
          </tr>
        </thead>
      )}
      <tbody>
        {sortedBody.map((row, i) => (
          <tr key={i}>
            {row.children.map((cell, j) => (
              <td key={j}>
                <RenderInline children_={cell.children} />
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function RenderInline({ children_ }: { children_: PhrasingContent[] }) {
  // Inline raw HTML in mdast comes in as separate nodes for the open
  // and close tag (e.g. `<em>italic</em>` is html "<em>" + text
  // "italic" + html "</em>"). Sanitizing each node alone would balance
  // the open tag to an empty `<em></em>` and drop the orphan close, so
  // we buffer adjacent text+html siblings into one HTML string and
  // sanitize the run as a whole. Any other phrasing node (link, code,
  // strong, image, math, etc.) flushes the buffer and renders via the
  // normal React path.
  const out: ReactNode[] = [];
  let buffer: PhrasingContent[] = [];

  const flush = () => {
    if (buffer.length === 0) return;
    if (buffer.every((n) => n.type === "text")) {
      const text = (buffer as Text[]).map((n) => n.value).join("");
      out.push(<Fragment key={out.length}>{text}</Fragment>);
    } else {
      const html = buffer
        .map((n) =>
          n.type === "text"
            ? escapeHtml((n as Text).value)
            : (n as { value: string }).value,
        )
        .join("");
      const safe = sanitizeHtml(html);
      if (safe) {
        out.push(
          <span key={out.length} dangerouslySetInnerHTML={{ __html: safe }} />,
        );
      }
    }
    buffer = [];
  };

  for (const node of children_) {
    if (node.type === "text" || node.type === "html") {
      buffer.push(node);
    } else {
      flush();
      out.push(<RenderInlineNode key={out.length} node={node} />);
    }
  }
  flush();
  return <>{out}</>;
}

function RenderInlineNode({ node }: { node: PhrasingContent }) {
  switch (node.type) {
    case "text":
      return <>{(node as Text).value}</>;
    case "strong":
      return (
        <strong>
          <RenderInline children_={node.children} />
        </strong>
      );
    case "emphasis":
      return (
        <em>
          <RenderInline children_={node.children} />
        </em>
      );
    case "inlineCode":
      return <code>{node.value}</code>;
    case "link":
      return (
        <LinkNode node={node}>
          {<RenderInline children_={node.children} />}
        </LinkNode>
      );
    case "break":
      return <br />;
    case "delete":
      return (
        <del>
          <RenderInline children_={node.children} />
        </del>
      );
    case "image":
      return <InlineImage node={node as Image} />;
    case "inlineMath":
      return <InlineMathNode node={node as InlineMath} />;
    case "footnoteReference":
      return <FootnoteRef node={node as FootnoteReference} />;
    case "html":
      // Inline html nodes are buffered and rendered by RenderInline,
      // which sanitizes paired open/close tags as one chunk. If one
      // ever reaches here directly, drop it rather than half-render.
      return null;
    default:
      return null;
  }
}

function LinkNode({
  node,
  children,
}: {
  node: { url: string; title?: string | null };
  children: ReactNode;
}) {
  const ctx = useContext(InlineCtx);
  const href = safeHref(node.url);
  if (!href) {
    return (
      <span className="link-blocked" title="Blocked link scheme">
        {children}
      </span>
    );
  }
  return (
    <a
      href={href}
      title={node.title ?? undefined}
      onClick={(e) => {
        if (!ctx) return;
        // Preserve middle/cmd-click → let the OS handle it (browser
        // window etc.) by not preventing default.
        if (e.metaKey || e.ctrlKey || e.button !== 0) return;
        e.preventDefault();
        ctx.onLinkClick(href);
      }}
    >
      {children}
    </a>
  );
}

// ─── Images ──────────────────────────────────────────────────────────

function ImageBlock({
  node,
  planPath,
}: {
  node: Image;
  planPath: string | null;
}) {
  const ctx = useContext(InlineCtx);
  const [trustOverride, setTrustOverride] = useState(false);
  const resolved = resolveImageSrc(planPath, node.url, {
    remoteAllowed: (ctx?.remoteAllowed ?? true) || trustOverride,
  });
  const alt = node.alt ?? "";
  if (resolved.blocked && resolved.reason === "untrusted") {
    return (
      <RemoteImagePlaceholder
        rawRef={node.url}
        alt={alt}
        onLoad={() => setTrustOverride(true)}
      />
    );
  }
  if (resolved.blocked) {
    return <BrokenImage rawRef={node.url} reason="blocked" />;
  }
  return (
    <figure className="md-image-figure">
      <img
        src={resolved.src}
        alt={alt}
        title={node.title ?? undefined}
        loading="lazy"
        // Kill referer fingerprinting on remote loads. Always set the
        // attribute (cheap, and harmless for the `specrider-img:`
        // protocol) so we don't have to branch in the JSX.
        referrerPolicy="no-referrer"
        crossOrigin={resolved.remote ? "anonymous" : undefined}
        onError={(e) => onImageError(e, node.url)}
      />
    </figure>
  );
}

function InlineImage({ node }: { node: Image }) {
  const ctx = useContext(InlineCtx);
  const [trustOverride, setTrustOverride] = useState(false);
  const resolved = resolveImageSrc(ctx?.planPath ?? null, node.url, {
    remoteAllowed: (ctx?.remoteAllowed ?? true) || trustOverride,
  });
  if (resolved.blocked && resolved.reason === "untrusted") {
    return (
      <RemoteImagePlaceholder
        rawRef={node.url}
        alt={node.alt ?? ""}
        inline
        onLoad={() => setTrustOverride(true)}
      />
    );
  }
  if (resolved.blocked) {
    return <BrokenImage rawRef={node.url} reason="blocked" inline />;
  }
  return (
    <img
      className="md-image-inline"
      src={resolved.src}
      alt={node.alt ?? ""}
      title={node.title ?? undefined}
      loading="lazy"
      referrerPolicy="no-referrer"
      crossOrigin={resolved.remote ? "anonymous" : undefined}
      onError={(e) => onImageError(e, node.url)}
    />
  );
}

function RemoteImagePlaceholder({
  rawRef,
  alt,
  inline,
  onLoad,
}: {
  rawRef: string;
  alt: string;
  inline?: boolean;
  /** Called when the user opts to load this single image inline,
   *  flipping the parent's per-image override and re-resolving the
   *  src as if the workspace were trusted (just for this image). */
  onLoad: () => void;
}) {
  const trust = useWorkspaceTrust();
  const [menu, setMenu] = useState<{ left: number; top: number } | null>(null);
  const Tag = inline ? "span" : "div";
  const label = alt ? `external image (${alt})` : "external image";
  const onContextMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    setMenu({ left: e.clientX, top: e.clientY });
  };
  const items: ContextMenuItem[] = [
    {
      label: "Load image",
      onSelect: onLoad,
    },
    { divider: true, label: "" },
    {
      label: "Trust workspace",
      onSelect: () => {
        // Flipping trust re-renders MarkdownRender with `remoteAllowed:
        // true`, so this image (and every other remote ref in the doc)
        // resolves to its real src on the next pass.
        void trust.set("trusted");
      },
    },
  ];
  return (
    <>
      <Tag
        className={`img-remote-placeholder${inline ? " inline" : ""}`}
        role="button"
        tabIndex={0}
        title={`${rawRef}\nClick to load this image. Right-click for more options.`}
        aria-label={`Load ${label}`}
        onClick={onLoad}
        onContextMenu={onContextMenu}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            onLoad();
          }
        }}
      >
        [{label} · click to load]
      </Tag>
      {menu && (
        <ContextMenu
          anchor={menu}
          items={items}
          onClose={() => setMenu(null)}
        />
      )}
    </>
  );
}

function BrokenImage({
  rawRef,
  reason,
  inline,
}: {
  rawRef: string;
  reason: "blocked" | "missing";
  inline?: boolean;
}) {
  const Tag = inline ? "span" : "div";
  const label =
    reason === "blocked"
      ? `[image blocked: ${rawRef}]`
      : `[image not found: ${rawRef}]`;
  return <Tag className="img-broken">{label}</Tag>;
}

function onImageError(
  e: React.SyntheticEvent<HTMLImageElement>,
  rawRef: string,
) {
  const img = e.currentTarget;
  if (img.dataset.broken === "1") return;
  img.dataset.broken = "1";
  const span = document.createElement("span");
  span.className = "img-broken";
  span.textContent = `[image not found: ${rawRef}]`;
  img.replaceWith(span);
}

// ─── Math ────────────────────────────────────────────────────────────

function MathBlock({ node }: { node: MathNode }) {
  const html = useRenderedMath(node.value, true);
  if (html == null) {
    return (
      <pre className="math math-display">
        <code>{node.value}</code>
      </pre>
    );
  }
  return (
    <div
      className="math math-display"
      role="math"
      aria-label={node.value}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function InlineMathNode({ node }: { node: InlineMath }) {
  const html = useRenderedMath(node.value, false);
  if (html == null) {
    return <code>{node.value}</code>;
  }
  return (
    <span
      className="math math-inline"
      role="math"
      aria-label={node.value}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function useRenderedMath(src: string, displayMode: boolean): string | null {
  const [html, setHtml] = useState<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    setHtml(null);
    void Promise.all([import("katex/dist/katex.min.css"), import("./math")])
      .then(([, { renderMath }]) => {
        if (!cancelled) setHtml(renderMath(src, displayMode));
      })
      .catch(() => {
        if (!cancelled) setHtml(null);
      });
    return () => {
      cancelled = true;
    };
  }, [src, displayMode]);
  return html;
}

// ─── Mermaid ─────────────────────────────────────────────────────────

function currentMermaidTheme(): "light" | "dark" {
  return document.body.classList.contains("theme-dark") ? "dark" : "light";
}

function useMermaidTheme(): "light" | "dark" {
  const [theme, setTheme] = useState<"light" | "dark">(() =>
    currentMermaidTheme(),
  );
  useEffect(() => {
    const apply = () => setTheme(currentMermaidTheme());
    const obs = new MutationObserver(apply);
    obs.observe(document.body, {
      attributes: true,
      attributeFilter: ["class"],
    });
    obs.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["style", "class"],
    });
    return () => obs.disconnect();
  }, []);
  return theme;
}

function MermaidBlock({ source }: { source: string }) {
  const theme = useMermaidTheme();
  const [state, setState] = useState<
    | { status: "loading" }
    | { status: "ready"; svg: string }
    | { status: "error"; message: string }
  >({ status: "loading" });
  useEffect(() => {
    let cancelled = false;
    setState({ status: "loading" });
    void renderMermaid(source, theme).then((out) => {
      if (cancelled) return;
      if (out.error) {
        setState({ status: "error", message: out.error });
      } else {
        setState({ status: "ready", svg: out.svg });
      }
    });
    return () => {
      cancelled = true;
    };
  }, [source, theme]);
  if (state.status === "loading") {
    return <div className="mermaid-loading" aria-busy="true" />;
  }
  if (state.status === "error") {
    return (
      <pre className="mermaid-error">
        <code>{source}</code>
        <span className="mermaid-error-msg">{state.message}</span>
      </pre>
    );
  }
  // Try to extract the SVG's <title> child (Mermaid emits one when the
  // diagram has a title directive). Falls back to the generic label.
  const titleMatch = state.svg.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const ariaLabel = titleMatch?.[1]?.trim() || "Mermaid diagram";
  return (
    <div
      className="mermaid"
      role="img"
      aria-label={ariaLabel}
      dangerouslySetInnerHTML={{ __html: state.svg }}
    />
  );
}

// ─── Footnotes ───────────────────────────────────────────────────────

function collectFootnotes(root: Root): {
  footnoteOrdinals: Map<string, number>;
  footnoteDefinitions: FootnoteDefinition[];
} {
  // Walk in document order: every reference gets the next ordinal the
  // first time it appears. Definitions that are never referenced still
  // render at the bottom but don't get a number.
  const ordinals = new Map<string, number>();
  let next = 1;
  const visit = (
    nodes: readonly RootContent[] | readonly PhrasingContent[],
  ) => {
    for (const node of nodes) {
      if (node.type === "footnoteReference") {
        const id = (node as FootnoteReference).identifier;
        if (!ordinals.has(id)) ordinals.set(id, next++);
        continue;
      }
      const kids = (node as { children?: unknown }).children;
      if (Array.isArray(kids)) {
        visit(kids as readonly PhrasingContent[]);
      }
    }
  };
  visit(root.children as readonly RootContent[]);

  const definitions: FootnoteDefinition[] = [];
  for (const child of root.children) {
    if (child.type === "footnoteDefinition") {
      definitions.push(child as FootnoteDefinition);
    }
  }
  // Stable sort so unreferenced defs trail referenced ones.
  definitions.sort((a, b) => {
    const ai = ordinals.get(a.identifier) ?? Number.MAX_SAFE_INTEGER;
    const bi = ordinals.get(b.identifier) ?? Number.MAX_SAFE_INTEGER;
    return ai - bi;
  });
  return { footnoteOrdinals: ordinals, footnoteDefinitions: definitions };
}

function FootnoteRef({ node }: { node: FootnoteReference }) {
  const ctx = useContext(InlineCtx);
  const ord = ctx?.footnoteOrdinals.get(node.identifier);
  if (!ord) return null;
  const id = encodeURIComponent(node.identifier);
  return (
    <sup className="footnote-ref">
      <a
        href={`#fn-${id}`}
        id={`fnref-${id}`}
        onClick={(e) => {
          e.preventDefault();
          const target = document.getElementById(`fn-${id}`);
          if (target) {
            target.scrollIntoView({
              behavior: scrollBehavior(),
              block: "center",
            });
            target.classList.add("footnote-target-flash");
            window.setTimeout(
              () => target.classList.remove("footnote-target-flash"),
              1200,
            );
          }
        }}
      >
        [{ord}]
      </a>
    </sup>
  );
}

function FootnotesAside({
  definitions,
  ordinals,
}: {
  definitions: FootnoteDefinition[];
  ordinals: Map<string, number>;
}) {
  return (
    <aside className="footnotes">
      <ol>
        {definitions.map((def) => {
          const ord = ordinals.get(def.identifier);
          const id = encodeURIComponent(def.identifier);
          return (
            <li key={def.identifier} id={`fn-${id}`}>
              {ord != null && <span className="footnote-ord">{ord}.</span>}
              <FootnoteBody node={def} />
              <a
                href={`#fnref-${id}`}
                className="footnote-back"
                aria-label="Return to reference"
                onClick={(e) => {
                  e.preventDefault();
                  const target = document.getElementById(`fnref-${id}`);
                  if (target) {
                    target.scrollIntoView({
                      behavior: scrollBehavior(),
                      block: "center",
                    });
                    target.classList.add("footnote-target-flash");
                    window.setTimeout(
                      () => target.classList.remove("footnote-target-flash"),
                      1200,
                    );
                  }
                }}
              >
                ↩
              </a>
            </li>
          );
        })}
      </ol>
    </aside>
  );
}

function FootnoteBody({ node }: { node: FootnoteDefinition }) {
  return (
    <>
      {node.children.map((child, i) => {
        if (child.type === "paragraph") {
          return (
            <span key={i} className="footnote-text">
              <RenderInline children_={(child as Paragraph).children} />
            </span>
          );
        }
        return null;
      })}
    </>
  );
}

export function listHeadings(
  root: Root,
): { id: string; depth: number; text: string }[] {
  const out: { id: string; depth: number; text: string }[] = [];
  for (const child of root.children) {
    if (child.type === "heading") {
      const text = mdastToString(child);
      out.push({ id: slugify(text), depth: child.depth, text });
    }
  }
  return out;
}
