#!/usr/bin/env bash
set -euo pipefail

target="${1:-${TMPDIR:-/tmp}/specrider-perf-fixture}"
commit_count="${PERF_COMMITS:-520}"
markdown_lines="${PERF_MARKDOWN_LINES:-5000}"
diff_lines="${PERF_DIFF_LINES:-1000}"

if [[ -e "$target" ]]; then
  echo "Target already exists: $target" >&2
  echo "Remove it or pass a different target path." >&2
  exit 1
fi

mkdir -p "$target"
cd "$target"

git init -q
git config user.name "Specrider Perf Fixture"
git config user.email "perf-fixture@example.invalid"

mkdir -p docs/plans/active src
cat > README.md <<'EOF'
# Specrider perf fixture

Generated by scripts/perf-fixture.sh.
EOF

git add README.md
git commit -q -m "Initial fixture"

for i in $(seq 1 "$commit_count"); do
  file="src/history-$((i % 20)).txt"
  printf "history entry %04d\n" "$i" >> "$file"
  git add "$file"
  git commit -q -m "Fixture history commit $i"
done

{
  echo "# Perf Fixture Plan"
  echo
  for i in $(seq 1 "$markdown_lines"); do
    case $((i % 40)) in
      0)
        printf "## Section %04d\n\n" "$i"
        ;;
      1)
        printf -- "- [ ] Task %04d with enough text to exercise wrapping and checkbox rendering.\n" "$i"
        ;;
      2)
        echo
        echo '```ts'
        printf "export const value%04d = %d;\n" "$i" "$i"
        echo '```'
        echo
        ;;
      *)
        printf "Line %04d: This paragraph exists to make the Markdown preview large enough for parse, render, outline, and syntax highlighting traces.\n" "$i"
        ;;
    esac
  done
} > docs/plans/active/perf-fixture.md

git add docs/plans/active/perf-fixture.md
git commit -q -m "Add large markdown fixture"

for i in $(seq 1 "$diff_lines"); do
  printf "original diff line %04d\n" "$i"
done > src/large-diff.txt

git add src/large-diff.txt
git commit -q -m "Add large diff baseline"

for i in $(seq 1 "$diff_lines"); do
  printf "modified diff line %04d\n" "$i"
done > src/large-diff.txt

git add src/large-diff.txt
git commit -q -m "Large 1000 line diff fixture"

cat <<EOF
Created perf fixture repo:
  $target

Open this repo in Specrider, then use:
  docs/plans/active/perf-fixture.md

Large diff commit:
  $(git rev-parse --short HEAD) Large 1000 line diff fixture
EOF
