/** Curated subset of Google Fonts, filtered for body legibility.
 *  No display/decorative families in the body lists; mono category
 *  is for code-block use. The user can also type any free-form family
 *  name in the picker's text fallback (covers locally-installed fonts
 *  and Google Fonts not in this list). */
export type FontCategory = "serif" | "sans" | "mono" | "display";

export interface FontEntry {
  family: string;
  category: FontCategory;
}

export const GOOGLE_FONTS: FontEntry[] = [
  // ─── Serif ─────────────────────────────────────────────────────
  { family: "Newsreader", category: "serif" },
  { family: "Source Serif 4", category: "serif" },
  { family: "EB Garamond", category: "serif" },
  { family: "Crimson Pro", category: "serif" },
  { family: "Crimson Text", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "Spectral", category: "serif" },
  { family: "Merriweather", category: "serif" },
  { family: "Cormorant", category: "serif" },
  { family: "Cormorant Garamond", category: "serif" },
  { family: "Vollkorn", category: "serif" },
  { family: "Libre Caslon Text", category: "serif" },
  { family: "Libre Baskerville", category: "serif" },
  { family: "Lusitana", category: "serif" },
  { family: "Sorts Mill Goudy", category: "serif" },
  { family: "Tinos", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Cardo", category: "serif" },
  { family: "Petrona", category: "serif" },
  { family: "Faustina", category: "serif" },
  { family: "Gentium Plus", category: "serif" },
  { family: "Gentium Book Plus", category: "serif" },
  { family: "Bitter", category: "serif" },
  { family: "Domine", category: "serif" },
  { family: "Fraunces", category: "serif" },
  { family: "Literata", category: "serif" },
  { family: "Roboto Serif", category: "serif" },
  { family: "Trirong", category: "serif" },
  { family: "Marcellus", category: "serif" },
  { family: "Forum", category: "serif" },
  { family: "Halant", category: "serif" },
  { family: "Inria Serif", category: "serif" },
  { family: "Bodoni Moda", category: "serif" },
  { family: "Pridi", category: "serif" },
  { family: "Mate", category: "serif" },
  { family: "Volkhov", category: "serif" },
  { family: "Cormorant Infant", category: "serif" },
  { family: "Cormorant Upright", category: "serif" },
  { family: "Source Serif Pro", category: "serif" },
  { family: "Lateef", category: "serif" },
  { family: "Andada Pro", category: "serif" },
  { family: "Roboto Slab", category: "serif" },
  { family: "Slabo 27px", category: "serif" },

  // ─── Sans ──────────────────────────────────────────────────────
  { family: "Inter", category: "sans" },
  { family: "Source Sans 3", category: "sans" },
  { family: "Source Sans Pro", category: "sans" },
  { family: "Noto Sans", category: "sans" },
  { family: "IBM Plex Sans", category: "sans" },
  { family: "Manrope", category: "sans" },
  { family: "Public Sans", category: "sans" },
  { family: "Plus Jakarta Sans", category: "sans" },
  { family: "DM Sans", category: "sans" },
  { family: "Geologica", category: "sans" },
  { family: "Open Sans", category: "sans" },
  { family: "Roboto", category: "sans" },
  { family: "Atkinson Hyperlegible", category: "sans" },
  { family: "Karla", category: "sans" },
  { family: "Lato", category: "sans" },
  { family: "Mulish", category: "sans" },
  { family: "Outfit", category: "sans" },
  { family: "Onest", category: "sans" },
  { family: "Albert Sans", category: "sans" },
  { family: "Hanken Grotesk", category: "sans" },
  { family: "Figtree", category: "sans" },
  { family: "Be Vietnam Pro", category: "sans" },
  { family: "Sora", category: "sans" },
  { family: "Work Sans", category: "sans" },
  { family: "Rubik", category: "sans" },
  { family: "Nunito", category: "sans" },
  { family: "Nunito Sans", category: "sans" },
  { family: "Hind", category: "sans" },
  { family: "Hind Madurai", category: "sans" },
  { family: "Asap", category: "sans" },
  { family: "Cabin", category: "sans" },
  { family: "Mada", category: "sans" },
  { family: "Saira", category: "sans" },
  { family: "Heebo", category: "sans" },
  { family: "Maven Pro", category: "sans" },
  { family: "Barlow", category: "sans" },
  { family: "Encode Sans", category: "sans" },
  { family: "Mukta", category: "sans" },
  { family: "Poppins", category: "sans" },

  // ─── Mono ──────────────────────────────────────────────────────
  { family: "JetBrains Mono", category: "mono" },
  { family: "IBM Plex Mono", category: "mono" },
  { family: "Source Code Pro", category: "mono" },
  { family: "DM Mono", category: "mono" },
  { family: "Fira Code", category: "mono" },
  { family: "Fira Mono", category: "mono" },
  { family: "Roboto Mono", category: "mono" },
  { family: "Inconsolata", category: "mono" },
  { family: "Cousine", category: "mono" },
  { family: "Anonymous Pro", category: "mono" },
  { family: "Space Mono", category: "mono" },
  { family: "Noto Sans Mono", category: "mono" },
  { family: "Overpass Mono", category: "mono" },
  { family: "Red Hat Mono", category: "mono" },
  { family: "Spline Sans Mono", category: "mono" },
  { family: "Cutive Mono", category: "mono" },
  { family: "Share Tech Mono", category: "mono" },

  // ─── Display ───────────────────────────────────────────────────
  { family: "Playfair Display", category: "display" },
  { family: "Bricolage Grotesque", category: "display" },
  { family: "DM Serif Display", category: "display" },
  { family: "Big Shoulders Display", category: "display" },
  { family: "Old Standard TT", category: "display" },
];

export const GOOGLE_FONT_FAMILIES: Set<string> = new Set(
  GOOGLE_FONTS.map((f) => f.family),
);
